-- Generated by scripts/bootstrap_input.py; original PDFs stay outside Git.
--> statement-breakpoint
INSERT INTO sources (id,kind,title,canonical_url,language,license,visibility,status,created_by,created_at,current_version_id) VALUES ('src_fb87aaf72d699df68d35','file','CELEX 32017D2075 DE TXT',NULL,'de','unknown','public','active','bootstrap','2026-08-02T10:25:48Z',NULL) ON CONFLICT(id) DO UPDATE SET title=excluded.title,canonical_url=excluded.canonical_url,language=excluded.language,license=excluded.license,visibility=excluded.visibility,status=excluded.status;
--> statement-breakpoint
INSERT INTO source_versions (id,source_id,sha256,normalized_sha256,size_bytes,media_type,original_filename,normalized_repo_path,converter_name,converter_version,fetch_time,created_at,supersedes_version_id,manifest_json) VALUES ('sv_ee9fc6b3ca6f222446aef1bb','src_fb87aaf72d699df68d35','ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c','6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710',400537,'application/pdf','CELEX_32017D2075_DE_TXT.pdf','sources/normalized/bootstrap/celex-32017d2075-de-txt.md','pdfplumber','0.11.9','2026-08-02T10:25:48Z','2026-08-02T10:25:48Z',NULL,'{"canonical_url":null,"contact_redaction":"email_phone_identified_contact_names_and_contact_address","converter":{"name":"pdfplumber","version":"0.11.9"},"imported_at":"2026-08-02T10:25:48Z","language":"de","license":"unknown","media_type":"application/pdf","normalized_repo_path":"sources/normalized/bootstrap/celex-32017d2075-de-txt.md","origin_page_url":"https://www.dbinfrago.com/web/schienennetz/netzzugang-und-regulierung/taf-tap-tsi/allgemein-11089206","original_filename":"CELEX_32017D2075_DE_TXT.pdf","page_count":5,"raw_binary_committed":false,"schema_version":1,"size_bytes":400537,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb","title":"CELEX 32017D2075 DE TXT","visibility":"public"}') ON CONFLICT(id) DO UPDATE SET sha256=excluded.sha256,normalized_sha256=excluded.normalized_sha256,size_bytes=excluded.size_bytes,media_type=excluded.media_type,original_filename=excluded.original_filename,normalized_repo_path=excluded.normalized_repo_path,converter_name=excluded.converter_name,converter_version=excluded.converter_version,fetch_time=excluded.fetch_time,supersedes_version_id=excluded.supersedes_version_id,manifest_json=excluded.manifest_json;
--> statement-breakpoint
INSERT INTO source_identities (identity_type,identity_hash,source_id,source_version_id,metadata_json,created_at) VALUES ('raw_sha256','ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c','src_fb87aaf72d699df68d35','sv_ee9fc6b3ca6f222446aef1bb','{"content_duplicate_group":null,"original_filename":"CELEX_32017D2075_DE_TXT.pdf"}','2026-08-02T10:25:48Z') ON CONFLICT(identity_type,identity_hash,source_id) DO UPDATE SET identity_type=excluded.identity_type,identity_hash=excluded.identity_hash,source_id=excluded.source_id,source_version_id=excluded.source_version_id,metadata_json=excluded.metadata_json;
--> statement-breakpoint
INSERT INTO source_identities (identity_type,identity_hash,source_id,source_version_id,metadata_json,created_at) VALUES ('normalized_sha256','6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710','src_fb87aaf72d699df68d35',NULL,'{"content_duplicate_group":null,"original_filename":"CELEX_32017D2075_DE_TXT.pdf"}','2026-08-02T10:25:48Z') ON CONFLICT(identity_type,identity_hash,source_id) DO UPDATE SET identity_type=excluded.identity_type,identity_hash=excluded.identity_hash,source_id=excluded.source_id,source_version_id=excluded.source_version_id,metadata_json=excluded.metadata_json;
--> statement-breakpoint
UPDATE sources SET current_version_id='sv_ee9fc6b3ca6f222446aef1bb' WHERE id='src_fb87aaf72d699df68d35';
--> statement-breakpoint
INSERT INTO wiki_pages (path,title,summary,commit_sha,content_sha,updated_at,metadata_json) VALUES ('wiki/sources/celex-32017d2075-de-txt.md','CELEX 32017D2075 DE TXT','14.11.2017 DE Amtsblatt der Europäischen Union L 295/69 DELEGIERTER BESCHLUSS (EU) 2017/2075 DER KOMMISSION vom 4. September 2017 zur Ersetzung des Anhangs VII der Richtlinie 2012/34/EU des Europäischen Parlaments und des Rates zur Schaffung eines einheitlichen europäischen Eisenbahnraums (Text von Bedeutung für den EWR) DIE EUROPÄISCHE KOMMISSION — gestützt','bootstrap:f8dfc1a873a48ca396ea046a5cc9add01212dc42661928708329bb77e6998fff','0e3056e4303e9771ff6543ac88f670753f3a0bf54daba5b94a928c1b543f6b5f','2026-08-02T10:25:48Z','{"bootstrap":true,"canonical_url":null,"license":"unknown","origin_page_url":"https://www.dbinfrago.com/web/schienennetz/netzzugang-und-regulierung/taf-tap-tsi/allgemein-11089206","source_id":"src_fb87aaf72d699df68d35","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}') ON CONFLICT(path) DO UPDATE SET title=excluded.title,summary=excluded.summary,commit_sha=excluded.commit_sha,content_sha=excluded.content_sha,updated_at=excluded.updated_at,metadata_json=excluded.metadata_json;
--> statement-breakpoint
DELETE FROM wiki_chunks WHERE page_path='wiki/sources/celex-32017d2075-de-txt.md';
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_51b8f1914156ff71873b78ab','wiki/sources/celex-32017d2075-de-txt.md',0,'Seite 1','14.11.2017 DE Amtsblatt der Europäischen Union L 295/69

DELEGIERTER BESCHLUSS (EU) 2017/2075 DER KOMMISSION

vom 4. September 2017

zur Ersetzung des Anhangs VII der Richtlinie 2012/34/EU des Europäischen Parlaments und des

Rates zur Schaffung eines einheitlichen europäischen Eisenbahnraums

(Text von Bedeutung für den EWR)

DIE EUROPÄISCHE KOMMISSION —

gestützt auf den Vertrag über die Arbeitsweise der Europäischen Union,

gestützt auf die Richtlinie 2012/34/EU des Europäischen Parlaments und des Rates vom 21. November 2012 zur

Schaffung eines einheitlichen europäischen Eisenbahnraums (1), insbesondere auf Artikel 43 Absatz 2,

in Erwägung nachstehender Gründe:

(1) Die Kapazitätszuweisung sollte auf transparente Weise erfolgen, und gleichzeitig sollten die Effizienz des

Zuweisungsverfahrens sowie die betrieblichen Belange aller an der Nutzung und Instandhaltung der Schieneninf

rastruktur beteiligten Interessengruppen berücksichtigt werden.

(2) Im Rahmen der Zuweisung von Infrastrukturkapazität sollten die Antragsteller die Möglichkeit erhalten, die

Einbeziehung von Kapazität in den jährlichen Netzfahrplan auch im Zeitraum zwischen dem Ende der

Antragsfrist für den Entwurf des Netzfahrplans und dem Netzfahrplanwechsel zu beantragen.

(3) Nach der Zuweisung der Zugtrassen sollte der Antragsteller vertraglich berechtigt sein, Vorschläge des Infrastruk

turbetreibers für Fahrplanänderungen abzulehnen oder anzunehmen.

(4) Damit die Infrastruktur und ihre Einrichtungen in gutem Zustand erhalten werden können und die Infrastruktur

im Einklang mit Markterfordernissen weiterentwickelt wird, sind zeitweilige Kapazitätsbeschränkungen

unumgänglich.

(5) Die Antragsteller sollten frühzeitig über anstehende Kapazitätsbeschränkungen informiert werden, damit sie ihre',221,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":1,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','7a8c14465ce208d001c6c31921ec73733fe337e90d3a28da699431cc8759b2d5');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_8ee7829ecb61963a51d52e20','wiki/sources/celex-32017d2075-de-txt.md',1,'Seite 1','betrieblichen und verkehrsbezogenen Erfordernisse an die Beschränkungen der Infrastrukturkapazität anpassen

können. Werden Informationen zu anstehenden Kapazitätsbeschränkungen bereits zu Beginn der Antragsfrist für

die Einbeziehung von Kapazität in den jährlichen Netzfahrplan veröffentlicht, sollte es seltener notwendig werden,

Änderungen hinsichtlich bereits zugewiesener Zugtrassen vorzunehmen.

(6) Bei der Wahl zwischen verschiedenen alternativen Kapazitätsbeschränkungen sollten die Infrastrukturbetreiber

nicht nur ihre eigenen Kosten, sondern auch die gewerblichen und betrieblichen Sachzwänge der betroffenen

Antragsteller sowie die Risiken einer Verkehrsverlagerung auf weniger umweltfreundliche Verkehrsträger

berücksichtigen.

(7) Die Infrastrukturbetreiber sollten transparente Kriterien für die Umleitung von Zügen und die Zuweisung

eingeschränkter Kapazität für verschiedene Verkehrsarten festlegen, veröffentlichen und anwenden. Dies können

sie entweder gemeinsam oder einzeln jeweils nur für ihre eigenen Kapazitätsbeschränkungen vornehmen.

(8) Die Infrastrukturbetreiber sollten ihre Schienennetz-Nutzungsbedingungen und Fahrplanerstellungsverfahren

anpassen, um sicherzustellen, dass die mit diesem Beschluss eingeführten neuen Bestimmungen für Kapazitätsbe

schränkungen rechtzeitig umgesetzt werden.

(9) Hinsichtlich netzübergreifend verkehrender Züge sollten sich die Infrastrukturbetreiber abstimmen, um die Folgen

von Kapazitätsbeschränkungen für den Verkehr zu minimieren und Bauarbeiten an einer bestimmten Strecke zu

synchronisieren oder Kapazitätsbeschränkungen auf einer Umleitungsstrecke zu vermeiden.

(10) Aus Gründen der Rechtssicherheit und angesichts der Zahl der erforderlichen Änderungen in Anhang VII der',191,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":1,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','f723c72aa777c1202837628b729f4dde00a62e0012b1eda4c3b927b570f29f25');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_3bd43373ab6dfb20807112d1','wiki/sources/celex-32017d2075-de-txt.md',2,'Seite 1','Richtlinie 2012/34/EU sollte der Anhang vollständig ersetzt werden. Zur Vereinfachung des Regulierungsrahmens

ist ein delegierter Beschluss das geeignete Rechtsinstrument, da er klare und detaillierte Bestimmungen enthält, die

von den Mitgliedstaaten nicht in nationales Recht umgesetzt werden müssen, sodass eine rasche und einheitliche

Durchführung in der gesamten Union gewährleistet ist.

(1) ABl. L 343 vom 14.12.2012, S. 32.',57,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":1,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','f29d6cffbf73e4c87177e6f31db61774c2e94a45e54f936de29e6394008f58d6');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_46fd7774155790f92cb5abfe','wiki/sources/celex-32017d2075-de-txt.md',3,'Seite 2','L 295/70 DE Amtsblatt der Europäischen Union 14.11.2017

(11) Infolge des Zeitpunkts des Netzfahrplanwechsels gemäß Nummer 2 des Anhangs und der Vorlaufzeiten für die

Koordinierung, Konsultation und Veröffentlichung der Kapazitätsbeschränkungen gemäß den Nummern 8 bis 11

des Anhangs können die Infrastrukturbetreiber die Anforderungen bezüglich der zweiten Veröffentlichungsrunde

gemäß den Nummern 8 bis 11 erstmals erst für den Netzfahrplanwechsel im Dezember 2019 und bezüglich der

ersten Veröffentlichungsrunde im Dezember 2020 erfüllen, während die Anforderungen der Nummer 12 sowie

der Nummern 14 bis 17 bereits für den Netzfahrplanwechsel im Dezember 2018 gelten.

(12) Die Richtlinie 2012/34/EU sollte daher entsprechend geändert werden —

HAT FOLGENDEN BESCHLUSS ERLASSEN:

Artikel 1

Anhang VII der Richtlinie 2012/34/EU wird durch den Anhang des vorliegenden Beschlusses ersetzt.

Artikel 2

Dieser Beschluss tritt am zwanzigsten Tag nach seiner Veröffentlichung im Amtsblatt der Europäischen Union in Kraft.

Geschehen zu Brüssel am 4. September 2017

Für die Kommission

Der Präsident

Jean-Claude JUNCKER',151,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":2,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','247674904d60640b07b29424684f4d78695aaba2bf8cd60f954cff7f2f3705a2');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_a7ae0767b0c524f059e06809','wiki/sources/celex-32017d2075-de-txt.md',4,'Seite 3','14.11.2017 DE Amtsblatt der Europäischen Union L 295/71

ANHANG

„ANHANG VII

ZEITPLAN DES ZUWEISUNGSVERFAHRENS

(gemäß Artikel 43)

(1) Der Netzfahrplan wird einmal im Kalenderjahr erstellt.

(2) Der Wechsel des Netzfahrplans erfolgt am zweiten Samstag im Dezember um 24.00 Uhr. Wird der Netzfahrplan

nach den Wintermonaten angepasst, insbesondere zur Berücksichtigung etwaiger Fahrplanänderungen im

regionalen Personenverkehr, so erfolgt die Umstellung am zweiten Samstag im Juni um 24.00 Uhr und bei Bedarf

zu anderen Terminen. Die Infrastrukturbetreiber können sich auf abweichende Termine verständigen; in diesem Fall

unterrichten sie die Kommission entsprechend, falls der internationale Verkehr betroffen sein könnte.

(3) Die Antragsfrist für die Zuweisung von Fahrwegkapazität zur Aufnahme in den Netzfahrplan endet höchstens

zwölf Monate vor dem Netzfahrplanwechsel. Nach Fristende eingegangene Anträge werden von den Infrastruktur

betreibern ebenfalls berücksichtigt.

(4) Die Infrastrukturbetreiber tragen dafür Sorge, dass spätestens elf Monate vor dem Netzfahrplanwechsel vorläufige

grenzüberschreitende Zugtrassen in Zusammenarbeit mit den anderen betroffenen Infrastrukturbetreibern festgelegt

sind. Die Infrastrukturbetreiber gewährleisten so weit wie möglich, dass diese Zugtrassen in den nachfolgenden

Verfahrensschritten beibehalten werden.

(5) Der Infrastrukturbetreiber erstellt und veröffentlicht spätestens vier Monate nach dem Ende der unter Nummer 3

genannten Frist einen Entwurf des Netzfahrplans.

(6) Der Infrastrukturbetreiber entscheidet über Anträge, die nach dem Ende der unter Nummer 3 genannten Frist

eingehen, nach einem in den Schienennetz-Nutzungsbedingungen veröffentlichten Verfahren.',213,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":3,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','d2cee764b74c8a8188e0e0815ffb8cb778b2e3128ae3e7af30d833399ac58dcb');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_1f8ffede773261460b390e5e','wiki/sources/celex-32017d2075-de-txt.md',5,'Seite 3','Der Infrastrukturbetreiber kann nur dann Änderungen hinsichtlich zugewiesener Zugtrassen vornehmen, wenn dies

erforderlich ist, um alle Trassenanträge bestmöglich in Einklang zu bringen, und wenn der Antragsteller, dem die

Trasse zugewiesen worden war, zustimmt. Der Infrastrukturbetreiber aktualisiert den Entwurf des Netzfahrplans

spätestens einen Monat vor dem Netzfahrplanwechsel, um alle nach dem Ende der unter Nummer 3 genannten

Frist zugewiesenen Zugtrassen einzubeziehen.

(7) Bei netzübergreifend verkehrenden Zügen, die voraussichtlich mit einer Verspätung von bis zu 10 Stunden und —

ab dem 14. Dezember 2019 — von bis zu 18 Stunden ankommen werden, betrachtet der Infrastrukturbetreiber

des anderen Netzes die Zugtrassen nicht als storniert und fordert nicht zur Beantragung einer anderen Zugtrasse

auf, selbst wenn er sich für die Zuweisung einer anderen Zugtrasse entscheidet, es sei denn, der Antragsteller

informiert den Infrastrukturbetreiber, dass der Zug die Grenze zu dem anderen Netz nicht überqueren wird. Der

Infrastrukturbetreiber teilt dem Antragsteller die aktualisierte oder neue Zugtrasse unverzüglich mit, einschließlich

(falls abweichend) der Verbindung zwischen dieser Zugtrassennummer und der Zugtrassennummer der stornierten

Zugtrasse.

(8) Hinsichtlich zeitweiliger Beschränkungen der Kapazität von Schienenstrecken, die durch Gründe wie z. B.

Infrastrukturarbeiten einschließlich der damit verbundenen Geschwindigkeitsbeschränkungen, Achslast, Zuglänge,

Traktion oder Lichtraumprofil bedingt sind (‚Kapazitätsbeschränkungen‘), mehr als sieben aufeinanderfolgende Tage

andauern und dazu führen, dass mehr als 30 % des geschätzten Verkehrsaufkommens auf einer Schienenstrecke pro',216,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":3,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','0d5d0c83fac3951ed2a51dc78b3f8221be9bd710c44adfc939553c112296a6c4');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_ff859a4b0e9271cdebb7e99e','wiki/sources/celex-32017d2075-de-txt.md',6,'Seite 3','Tag storniert, umgeleitet oder durch andere Verkehrsträger ersetzt wird, müssen die betroffenen Infrastruktur

betreiber alle Kapazitätsbeschränkungen sowie die vorläufigen Ergebnisse einer Konsultation der Antragsteller zum

ersten Mal, soweit bekannt, mindestens 24 Monate und zum zweiten Mal in aktualisierter Form mindestens

12 Monate vor dem betreffenden Netzfahrplanwechsel veröffentlichen.

(9) Zudem führen die betroffenen Infrastrukturbetreiber ein Verfahren ein, um diese Kapazitätsbeschränkungen mit

interessierten Antragstellern, den in Artikel 40 Absatz 1 genannten Vereinigungen von Infrastrukturbetreibern und

den wichtigsten Betreibern von betroffenen Serviceeinrichtungen bei der ersten Veröffentlichung zu erörtern, sofern

sie sich auf mehr als ein Netz auswirken, außer wenn die Infrastrukturbetreiber und Antragsteller vereinbaren, dass

ein solches Verfahren nicht erforderlich ist. Die gemeinsamen Gespräche müssen zur Fahrplanerstellung beitragen,

auch hinsichtlich der Bereitstellung von Umleitungsstrecken.',121,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":3,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','381be9f9d66f1aeb6688cf061c34c01782581bf8d5623d0057bc6f3f253fbac4');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_eb206caeb808f978209cc787','wiki/sources/celex-32017d2075-de-txt.md',7,'Seite 4','L 295/72 DE Amtsblatt der Europäischen Union 14.11.2017

(10) Bei der ersten Veröffentlichung von Kapazitätsbeschränkungen gemäß Nummer 8 leitet der Infrastrukturbetreiber

eine Konsultation der Antragsteller und der wichtigsten Betreiber von betroffenen Serviceeinrichtungen zu den

Kapazitätsbeschränkungen ein. Ist zwischen der ersten und der zweiten Veröffentlichung der Kapazitätsbe

schränkungen gemäß Nummer 11 eine Koordinierung erforderlich, konsultieren die Infrastrukturbetreiber die

Antragsteller und die wichtigsten Betreiber von Serviceeinrichtungen zwischen dem Ende dieser Koordinierung und

der zweiten Veröffentlichung der Kapazitätsbeschränkung ein zweites Mal.

(11) Vor der Veröffentlichung der Kapazitätsbeschränkungen gemäß Nummer 8 stimmen die betroffenen Infrastruktur

betreiber, einschließlich Infrastrukturbetreibern, die von einer Zugumleitung betroffen sein könnten, Kapazitätsbe

schränkungen, die zu einer Stornierung, Umleitung oder einen Ersatz durch andere Verkehrsträger führen könnten,

miteinander ab, wenn sich die Kapazitätsbeschränkungen auf mehr als ein Netz auswirken.

Die Koordinierung vor der zweiten Veröffentlichung muss zu folgenden Zeitpunkten abgeschlossen sein:

a) spätestens 18 Monate vor dem Netzfahrplanwechsel, wenn mehr als 50 % des geschätzten Verkehrsaufkommens

auf einer Schienenstrecke pro Tag für eine Dauer von mehr als 30 aufeinanderfolgenden Tagen storniert,

umgeleitet oder durch andere Verkehrsträger ersetzt wird;

b) spätestens 13 Monate und 15 Tage vor dem Netzfahrplanwechsel, wenn mehr als 30 % des geschätzten

Verkehrsaufkommens auf einer Schienenstrecke pro Tag für eine Dauer von mehr als sieben aufeinander

folgenden Tagen storniert, umgeleitet oder durch andere Verkehrsträger ersetzt wird;',218,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":4,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','3f0fd603a7e6be8c73fcc48d41b9c66a5f23fc785131dbc329d0cc407d83276c');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_3553237a533869c98ce0a180','wiki/sources/celex-32017d2075-de-txt.md',8,'Seite 4','c) spätestens 13 Monate und 15 Tage vor dem Netzfahrplanwechsel, wenn mehr als 50 % des geschätzten

Verkehrsaufkommens auf einer Schienenstrecke pro Tag für eine Dauer von bis zu sieben aufeinanderfolgenden

Tagen storniert, umgeleitet oder durch andere Verkehrsträger ersetzt wird.

Soweit erforderlich, laden die Infrastrukturbetreiber die auf den betroffenen Strecken tätigen Antragsteller und die

wichtigsten Betreiber der betroffenen Serviceeinrichtungen zur Teilnahme an dieser Koordinierung ein.

(12) Hinsichtlich Kapazitätsbeschränkungen mit einer Dauer von bis zu sieben aufeinanderfolgenden Tagen, die nicht

gemäß Nummer 8 veröffentlicht werden müssen, aber dazu führen, dass mehr als 10 % des geschätzten Verkehrs

aufkommens auf einer Schienenstrecke pro Tag storniert, umgeleitet oder durch andere Verkehrsträger ersetzt wird,

und die in der folgenden Fahrplanperiode auftreten und dem Infrastrukturbetreiber spätestens 6 Monate und

15 Tage vor dem Netzfahrplanwechsel bekannt werden, konsultiert der Infrastrukturbetreiber die betroffenen

Antragsteller zu den vorgesehenen Kapazitätsbeschränkungen und teilt die aktualisierten Kapazitätsbeschränkungen

mindestens vier Monate vor dem Netzfahrplanwechsel mit. Der Infrastrukturbetreiber stellt die Einzelheiten zu den

angebotenen Zugtrassen für Personenzüge spätestens vier Monate und für Güterzüge spätestens einen Monat vor

dem Beginn der Kapazitätsbeschränkung bereit, außer wenn der Infrastrukturbetreiber und die betroffenen

Antragsteller eine kürzere Vorlaufzeit vereinbaren.

(13) Die Infrastrukturbetreiber können auf der Grundlage einer Konsultation mit Antragstellern und den Betreibern von

Serviceeinrichtungen entscheiden, strengere Schwellen für Kapazitätsbeschränkungen anzuwenden, die auf',215,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":4,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','760e9324420fb29768331771355e76a35e98a504e6e68fffc2b2f353127af997');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_1ffe4f2f60bc8f3e2c677829','wiki/sources/celex-32017d2075-de-txt.md',9,'Seite 4','niedrigeren Prozentsätzen des geschätzten Verkehrsaufkommens oder einer kürzeren Dauer beruhen, als nach

diesem Anhang erforderlich wäre, oder neben den Kriterien aus diesem Anhang weitere Kriterien anzuwenden. Sie

veröffentlichen die Schwellen und Kriterien für die Zusammenfassung von Kapazitätsbeschränkungen in ihren

Schienennetz-Nutzungsbedingungen nach Anhang IV Nummer 3.

(14) Der Infrastrukturbetreiber kann entscheiden, die unter den Nummer 8 bis 12 genannten Fristen nicht anzuwenden,

wenn die Kapazitätsbeschränkung für die Wiederherstellung eines sicheren Zugbetriebs erforderlich ist, der

Zeitpunkt der Beschränkungen nicht der Kontrolle des Infrastrukturbetreibers unterliegt, die Anwendung dieser

Fristen nicht kostenwirksam oder mit nicht zu vertretenden Nachteilen für Lebensdauer oder Zustand von Anlagen

verbunden wäre oder wenn alle betroffenen Antragsteller zustimmen. In diesen Fällen sowie im Falle anderer

Kapazitätsbeschränkungen, die nicht gemäß anderen Bestimmungen dieses Anhangs einer Konsultation unterzogen

werden müssen, konsultiert der Infrastrukturbetreiber die betroffenen Antragsteller und die wichtigsten Betreiber

von Serviceeinrichtungen umgehend.

(15) Die vom Infrastrukturbetreiber bei Maßnahmen gemäß den Nummern 8, 12 oder 14 bereitzustellenden

Informationen müssen Folgendes umfassen:

a) den vorgesehenen Tag,

b) die Tageszeit und, sobald möglich, Uhrzeit des Beginns und Endes der Kapazitätsbeschränkung,

c) den von der Kapazitätsbeschränkung betroffenen Streckenabschnitt und

d) gegebenenfalls die Kapazität der Umleitungsstrecken.

Der Infrastrukturbetreiber veröffentlicht diese Informationen oder einen entsprechenden Link zur Fundstelle gemäß',202,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":4,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','20b9b1cd2fcf196ffa7a9a07c0c53759bce75a9f11faeee1f990816417239a32');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_c1c8e0762dc94e8f96134e35','wiki/sources/celex-32017d2075-de-txt.md',10,'Seite 4','Anhang IV Nummer 3 in seinen Schienennetz-Nutzungsbedingungen. Der Infrastrukturbetreiber muss diese

Informationen laufend aktualisieren.',14,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":4,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','8f58242004b45682875dbd3f9e53a9280bc0831a1649bcb848e3cec8bc659d77');
--> statement-breakpoint
INSERT INTO wiki_chunks (id,page_path,ordinal,heading_path,text,token_count,source_refs_json,content_sha) VALUES ('chunk_ae0509aa0537a0010b129ff2','wiki/sources/celex-32017d2075-de-txt.md',11,'Seite 5','14.11.2017 DE Amtsblatt der Europäischen Union L 295/73

(16) Hinsichtlich Kapazitätsbeschränkungen, die mindestens 30 aufeinanderfolgende Tage lang andauern und mehr als

50 % des geschätzten Verkehrsaufkommens auf einer Schienenstrecke betreffen, muss der Infrastrukturbetreiber den

Antragstellern auf deren Anfrage hin während der ersten Konsultationsrunde einen Vergleich der Bedingungen bei

mindestens zwei alternativen Kapazitätsbeschränkungen bereitstellen. Der Infrastrukturbetreiber gestaltet diese

Alternativen gemeinsam mit den Antragstellern anhand der Angaben, die ihm die Antragsteller zum Zeitpunkt

ihrer Anfrage bereitstellen.

Der Vergleich muss für jede Alternative mindestens Folgendes umfassen:

a) die Dauer der Kapazitätsbeschränkung,

b) die zu erwartenden ungefähr zu zahlenden Infrastrukturentgelte,

c) die verfügbare Kapazität auf Umleitungsstrecken,

d) die verfügbaren alternativen Strecken und

e) die ungefähren Fahrtzeiten.

Bevor er zwischen den alternativen Kapazitätsbeschränkungen wählt, konsultiert der Infrastrukturbetreiber die

interessierten Antragsteller und berücksichtigt die Auswirkungen der verschiedenen Alternativen auf diese

Antragsteller und die Nutzer der Dienste.

(17) Im Falle von Kapazitätsbeschränkungen, die mehr als 30 aufeinanderfolgende Tage andauern und mehr als 50 %

des geschätzten Verkehrsaufkommens auf einer Schienenstrecke betreffen, muss der Infrastrukturbetreiber Kriterien

festlegen, welche Züge jeder Verkehrsart umgeleitet werden sollten, und dabei die gewerblichen und betrieblichen

Sachzwänge des Antragstellers berücksichtigen, soweit diese betrieblichen Sachzwänge nicht aus unternehmerischen

oder organisatorischen Entscheidungen des Antragstellers resultieren, unbeschadet des Ziels gemäß Artikel 30',205,'{"canonical_url":null,"normalized_sha256":"6f9374549aa7339e6c8e0655477ac6f91fae79fee7391e4033e1a0a5b952c710","page":5,"source_id":"src_fb87aaf72d699df68d35","source_sha256":"ee9fc6b3ca6f222446aef1bb77496672f1cf3083ed0a9ef6d493178d4e70839c","source_version_id":"sv_ee9fc6b3ca6f222446aef1bb"}','6040efd041cafbb9bb054277fb87d508ca3a4dae26f61c79ca6c1937402a1f84');
--> statement-breakpoint
